# Generated by Django 6.0.1 on 2026-01-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                ("id_kategori", models.IntegerField(primary_key=True, serialize=False)),
                ("nama_kategori", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "kategori",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id_status", models.IntegerField(primary_key=True, serialize=False)),
                ("nama_status", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "status",
            },
        ),
        migrations.CreateModel(
            name="Produk",
            fields=[
                ("id_produk", models.IntegerField(primary_key=True, serialize=False)),
                ("nama_produk", models.CharField(max_length=255)),
                ("harga", models.PositiveIntegerField()),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produk.kategori",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="produk.status"
                    ),
                ),
            ],
            options={
                "db_table": "produk",
            },
        ),
    ]
