# Generated by Django 6.0.1 on 2026-01-29 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produk", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produk",
            name="harga",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="produk",
            name="kategori",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produk",
                to="produk.kategori",
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produk",
                to="produk.status",
            ),
        ),
        migrations.AlterModelTable(
            name="kategori",
            table=None,
        ),
        migrations.AlterModelTable(
            name="produk",
            table=None,
        ),
        migrations.AlterModelTable(
            name="status",
            table=None,
        ),
    ]
